plugins {
    alias(libs.plugins.android.application)
    id("com.google.gms.google-services")
}

android {
    def newsApiKey = project.findProperty("NEWS_API_KEY") ?: ""

    namespace 'com.example.hldsn'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.hldsn"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "NEWS_API_KEY", "\"${newsApiKey}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
        }
        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            res.srcDirs = [
                    'src/main/res',
                    'src/main/res_chats',
                    'src/main/res_community_reports',
                    'src/main/res_main_screens',
                    'src/main/res_notification',
                    'src/main/res_others',
                    'src/main/res_safety_tips',
                    'src/main/res_volunteer',
                    'src/main/res_user_profile'
            ]
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-firestore:24.11.1'
    implementation("com.google.firebase:firebase-auth")
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'




    implementation(platform("com.google.firebase:firebase-bom:34.6.0"))
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation libs.firebase.auth
    implementation libs.firebase.storage
    implementation libs.swiperefreshlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}